"""Build an Orchestrate-compatible OpenAPI 3.0 contract from the FastAPI app."""

from copy import deepcopy
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fastapi.openapi.utils import get_openapi
from ibm_watsonx_orchestrate.agent_builder.tools.openapi_tool import create_openapi_json_tool
from openapi_spec_validator import validate
import yaml

from api.main import app

SERVER_TOKEN = "${SHIPPING_API_URL}"
TEMPLATE = ROOT / "tools" / "shipping_eligibility.openapi.yaml"


def to_openapi_30(value):
    """Convert the only 3.1-only construct in our nonnullable models: const."""
    if isinstance(value, list):
        return [to_openapi_30(item) for item in value]
    if isinstance(value, dict):
        result = {key: to_openapi_30(item) for key, item in value.items() if key != "const"}
        if "const" in value:
            result["enum"] = [value["const"]]
        return result
    return value


def generated_contract(server: str = SERVER_TOKEN) -> dict:
    contract = get_openapi(title=app.title, version=app.version, description=app.description,
                           routes=app.routes, openapi_version="3.0.3")
    contract = to_openapi_30(contract)
    contract["servers"] = [{"url": server}]
    return contract


def validate_contract(contract: dict) -> None:
    validate(contract)
    tool = create_openapi_json_tool(deepcopy(contract), "/eligibility", "GET", "200")
    spec = tool.__tool_spec__
    if spec.name != "evaluate_rate_eligibility":
        raise ValueError("OpenAPI operationId must match the rate agent's tool name.")
    expected = {"query_monthly_volume", "query_destination_mix", "query_business_type"}
    if set(spec.input_schema.required) != expected:
        raise ValueError("Imported ADK tool arguments differ from the rate agent contract.")
    spec.model_dump_json()


def load_template() -> dict:
    contract = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8"))
    if contract != generated_contract():
        raise ValueError("Tool YAML is stale relative to the API. Run `make openapi`, then `make test`.")
    check = deepcopy(contract)
    check["servers"] = [{"url": "https://shipping-api.example.invalid"}]
    validate_contract(check)  # Offline; the example hostname is never called.
    return contract


def write_template() -> None:
    contract = generated_contract()
    check = deepcopy(contract)
    check["servers"] = [{"url": "https://shipping-api.example.invalid"}]
    validate_contract(check)
    TEMPLATE.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE.write_text("# Generated by `make openapi`. Render the server placeholder before import.\n"
                        + yaml.safe_dump(contract, sort_keys=False), encoding="utf-8")
    print(f"Wrote {TEMPLATE.relative_to(ROOT)} from the API schema.")


if __name__ == "__main__":
    write_template()
